import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import { Inter, Roboto_Condensed } from 'next/font/google'
import Providers from "./providers";
import { DataStoreProvider } from "@/providers/data-store-provider";
import { UserProvider } from '@auth0/nextjs-auth0/client';


// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter"
})

const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-roboto-condensed"
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto_condensed.variable}`}>
          <Providers>
            <DataStoreProvider>
              {children}
            </DataStoreProvider>
          </Providers>
        </body>
      </UserProvider>
    </html>
  );
}
